### PR TITLE
rename package from `harmony` to `harmony_service_lib`

### PR DESCRIPTION
**Pull request by danielfromearth**
## Jira Issue ID
[HARMONY-1781](https://bugs.earthdata.nasa.gov/browse/HARMONY-1781)

## Description
Change the package name from `harmony` to `harmony_service_lib`.

## PR Acceptance Checklist
* [x] Acceptance criteria met
* [x] Tests added/updated (if needed) and passing
* [ ] Documentation updated (if needed)

### CODE REVIEW

**Comment by owenlittlejohns** [comment]
I think it might be worth locally trying to run `make build` to test out the new version of `setuptools` - when I just tried bumping that to 74.1.2, I get errors (which were resolved with [this](https://github.com/pypa/setuptools/issues/4483#issuecomment-2328382713) and bumping `safety`). But trying the fix ends up getting to deprecation warnings about using `setup.py`.

**Comment by chris-durbin** [comment]
Thanks for implementing this PR! We're trying to figure out the issue Owen is mentioning (and reconciling with Owen's PR). When we merge this in we'll plan to update the major version since it will be a breaking change for everyone.

**Review by chris-durbin — APPROVED** [review]
Successfully tested with harmony-service-example.

**Review by ygliuvt — APPROVED** [review]
Tested successfully with harmony-service-example locally.

**Review by owenlittlejohns — COMMENTED** [review]
I think these changes look functionally great. I used the library locally, and it works nicely. One thing I did spot was a bunch of doc-string comments that are now out of date. I can push a commit up with those now, though.

**Review by owenlittlejohns — APPROVED** [review]

**Comment by danielfromearth** [comment]
Thanks @owenlittlejohns, @chris-durbin, @ygliuvt for your help in making this name change happen!

**Pull request merged**
